export default {
    dataList: [
        {                        
            category: 'devices',
            listInfo: [
                {
                    id: 1,                    
                    src: require('../../assets/img/001.jpg'),
                    title: 'MY PHONE',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                },
                {
                    id: 6,                    
                    src: require('../../assets/img/001.jpg'),
                    title: 'MY PHONE 2',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                },
                {
                    id: 7,                    
                    src: require('../../assets/img/001.jpg'),
                    title: 'MY PHONE 3',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                }
            ]            
        },
        {            
            category: 'applications',
            listInfo: [
                {
                    id: 2,                    
                    src: require('../../assets/img/002.jpg'),
                    title: 'MY APP',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                },
                {
                    id: 3,                    
                    src: require('../../assets/img/003.jpg'),
                    title: 'MY DASHBOARD',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                },
                {
                    id: 4,                    
                    src: require('../../assets/img/002.jpg'),
                    title: 'MY DASHBOARD 2',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                },
                {
                    id: 5,                    
                    src: require('../../assets/img/001.jpg'),
                    title: 'MY DASHBOARD 3',
                    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar ligula non placerat ullamcorper. Suspendisse suscipit mi eu commodo suscipit. Curabitur sit amet augue ac urna bibendum placerat vitae sed velit. Aenean eu rutrum augue. Quisque varius eros sit amet sagittis auctor. Fusce ut est nec nisl rhoncus euismod vel sed justo. Fusce molestie sagittis nunc, quis elementum quam porttitor at. Suspendisse fringilla vitae elit vel consequat. Etiam interdum dui facilisis purus convallis, eleifend aliquam elit sollicitudin. Vestibulum mollis cursus venenatis. Nulla eu dolor a elit semper porta ut sed orci. Praesent tincidunt condimentum molestie. Maecenas ligula mauris, feugiat id sapien ac, pretium tempor ipsum. Suspendisse id purus sit amet ex faucibus rhoncus ut non elit. Sed a suscipit lectus, quis luctus lacus.'
                }
            ]            
        }        
    ]
}